theme: jekyll-theme-hacker
show_downloads: ["true"]
title: [TI-Chromnect]
description: [The goal of this program is to have functional software to traeeeensfer data onto TI calculators that works in a web browser.]
